server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: hegx
    password: 123456
    #，每次启动程序，程序都会运行schema.sql文件，对数据库的数据操作
    schema: classpath:db/schema.sql
    #，每次启动程序，程序都会运行data.sql文件，对数据库的数据操作
    data: classpath:db/data.sql
    jpa:
      database: h2
      hibernate:
        ddl-auto: update
      show-sql: true
      h2:
        console:
          path: /h2-console
          enabled: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.szhn.hegx.bms

#showSql
logging:
  level:
    com:
      example:
        mapper : debug